[window]
opacity = 0.8

[font]
normal = { family = "Mononoki Nerd Font Mono", style = "Regular" }
bold = { family = "Mononoki Nerd Font Mono", style = "Bold"}
italic = { family = "Mononoki Nerd Font Mono", style = "Italic"}
bold_italic = { family = "Mononoki Nerd Font Mono", style = "Bold Italic"}
size = 16

[colors]
primary.foreground = "#00ff00"
