[window]
opacity = 0.95

[font]
normal = { family = "Mononoki Nerd Font Mono", style = "Regular" }
bold = { family = "Mononoki Nerd Font Mono", style = "Bold"}
italic = { family = "Mononoki Nerd Font Mono", style = "Italic"}
bold_italic = { family = "Mononoki Nerd Font Mono", style = "Bold Italic"}
size = 15

[colors]
primary.foreground = "#00dd00"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]
